# vi: ts=4 sw=4 ff=unix fenc=utf-8
# redntfy ビルドスクリプト
# DevShell モジュール経由で VC++ ビルド環境を初期化し、rc/cl でビルドする。
param([string]$Version = "0.0.0", [switch]$Release, [switch]$Test)
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot
$Version = $Version -replace '^v', ''

# vcpkg パス設定（VCPKG_INSTALLATION_ROOT 環境変数 → Scoop シム の優先順）
if ($env:VCPKG_INSTALLATION_ROOT) {
    $vcpkgRoot = $env:VCPKG_INSTALLATION_ROOT
}
else {
    $vcpkgCmd = (Get-Command vcpkg -ErrorAction Stop).Source
    $vcpkgRoot = Split-Path $vcpkgCmd
    $shimFile = [System.IO.Path]::ChangeExtension($vcpkgCmd, ".shim")
    if (Test-Path $shimFile) {
        $vcpkgReal = (Get-Content $shimFile |
            Where-Object { $_ -match "^path" } |
            ForEach-Object { ($_ -split '"')[1] } |
            Select-Object -First 1)
        if ($vcpkgReal) {
            $vcpkgRoot = Split-Path $vcpkgReal
        }
    }
}
$vcpkgInclude = "$vcpkgRoot\installed\x64-windows-static\include"
$vcpkgLib     = "$vcpkgRoot\installed\x64-windows-static\lib"

# 依存ライブラリのインストール（未インストール時のみ実行）
& "$vcpkgRoot\vcpkg.exe" install libebur128:x64-windows-static
if ($LASTEXITCODE) { exit 1 }

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { Write-Error "vswhere.exe が見つからない: $vswhere"; exit 1 }
$vsPath = & $vswhere -products '*' -latest -property installationPath
if (-not $vsPath) { Write-Error "Visual Studio / Build Tools が見つからない"; exit 1 }

$devShellDll = Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
Import-Module $devShellDll
Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=x64"

"#define APP_VERSION L`"$Version`"" | Set-Content -Encoding UTF8NoBOM out\version.h

# 単体テストのビルド（-Test 時のみ。rc は不要で、最適化なしでコンパイル時間を優先する）
# テストはコンソール exe のため main をエントリに明示し、main.cpp 側の wmain と共存させる
if ($Test) {
    cl /nologo /utf-8 /std:c++20 /EHsc /Od /I out\ /I "$vcpkgInclude" `
        /Foout\ /Feout\redntfy_test.exe `
        tests\test_main.cpp `
        /link /SUBSYSTEM:CONSOLE /ENTRY:mainCRTStartup `
        windowsapp.lib winhttp.lib shlwapi.lib shell32.lib propsys.lib gdi32.lib `
        "$vcpkgLib\ebur128.lib"
    if ($LASTEXITCODE) { exit 1 }
    exit 0
}

# VERSIONINFO 用の数値バージョン（カンマ区切り 4 数値）
# $Version は git describe 由来で "1.6.1-3-gabc1234-dirty" 等の形も取る。
# そのため先頭の major.minor.patch のみを採用する。第 4 数値は 0 固定、タグ未取得時は 0,0,0,0。
$verMatch = [regex]::Match($Version, '^(\d+)\.(\d+)\.(\d+)')
$verNum = if ($verMatch.Success) {
    "$($verMatch.Groups[1].Value),$($verMatch.Groups[2].Value),$($verMatch.Groups[3].Value),0"
}
else {
    "0,0,0,0"
}

# バージョン情報リソース用ヘッダを生成（resource.rc が include する）
# rc.exe の /d オプションでは文字列リテラルを渡せない。PowerShell から `\"` 付きで渡しても
# rc.exe はエスケープを解除せず `\` を構文エラー（RC2104）にするためだ。
# 代わりに定義をヘッダへ書き出す。生成先は out で、rc.exe には /I out を与える。
@(
    "// Generated by build.ps1. Do not edit.",  # ascii 出力のため英文にする
    "#define APP_VERSION_NUM $verNum",
    "#define APP_VERSION_STR `"$Version`""
) | Set-Content -Path out\version.rc.h -Encoding ascii

# /c65001 は .rc の既定コードページを UTF-8 に固定する。resource.rc は BOM なし UTF-8 で
# 日本語コメントを含み、無指定だと rc.exe が実行環境の ACP（日本語 Windows では CP932）で
# MBCS 走査するため、行末のバイトがリードバイト範囲に当たると改行を食って次行が消える。
rc /nologo /c65001 /I out /fo out\resource.res src\resource.rc
if ($LASTEXITCODE) { exit 1 }

# リリースモード時の追加フラグ
$clExtra   = if ($Release) { @('/DNDEBUG', '/GL', '/Gy') } else { @() }
$linkExtra = if ($Release) { @('/LTCG', '/OPT:REF', '/OPT:ICF') } else { @() }

cl /nologo /utf-8 /std:c++20 /EHsc /O2 @clExtra /I out\ /I "$vcpkgInclude" `
    /Foout\ /Feout\redntfy.exe `
    src\main.cpp out\resource.res `
    /link /SUBSYSTEM:WINDOWS /ENTRY:wmainCRTStartup @linkExtra `
    windowsapp.lib winhttp.lib shlwapi.lib shell32.lib propsys.lib gdi32.lib `
    "$vcpkgLib\ebur128.lib"
if ($LASTEXITCODE) { exit 1 }

# バージョン情報リソースの埋め込み検証
# 埋め込みが欠けてもビルドは通ってしまうため、ここで失敗させて見落としを防ぐ
$vi = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$PSScriptRoot\out\redntfy.exe")
if ($vi.FileDescription -ne "redntfy" -or $vi.ProductVersion -ne $Version) {
    Write-Error "VERSIONINFO 検証失敗: FileDescription='$($vi.FileDescription)' ProductVersion='$($vi.ProductVersion)' (expected '$Version')"
    exit 1
}
Write-Host "VERSIONINFO: $($vi.FileDescription) $($vi.ProductVersion)"
